version: '3.8'
services:
  web:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  ocr:
    build:
      context: ./OCR-Scan
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
