version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend-flask
      - backend-express
    networks:
      - app-network

  frontend:
    build:
      context: ./App
      dockerfile: Dockerfile
    networks:
      - app-network

  backend-flask:
    build:
      context: ./OCR-Scan
      dockerfile: Dockerfile
    networks:
      - app-network

  backend-express:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
